version: 2

jobs:
  checkout:
    working_directory: ~/ng8-boilerplate
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/ng8-boilerplate
  dependencies:
    working_directory: ~/ng8-boilerplate
    docker:
      - image: circleci/node:12-browsers
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/ng8-boilerplate/node_modules
  lint:
    working_directory: ~/ng8-boilerplate
    docker:
      - image: circleci/node:12-browsers
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: ESLint
          command: npm run lint:js
      - run:
          name: Prettier
          command: npm run prettier:check
  build:
    working_directory: ~/ng8-boilerplate
    docker:
      - image: circleci/node:12-browsers
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build:prod
      - save_cache:
          key: v0-build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/ng8-boilerplate/dist/ng8-boilerplate
  test:
    working_directory: ~/ng8-boilerplate
    docker:
      - image: circleci/node:12-browsers
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: npm run test:ci
      - run:
          name: E2E
          command: npm run e2e:ci

workflows:
  version: 2
  ci:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
      - lint:
          requires:
            - dependencies
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
