name: ci

on:
  push:
    branches:
      - ng-12
  pull_request:
    branches:
      - ng-12

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x', '14.x', '12.x']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci --no-progress
      - name: Lint
        run: npm run lint
      - name: ESLint
        run: npm run lint:js
      - name: Prettier
        run: npm run prettier:check
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:ci
