name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: ESLint
      run: npm run lint:js
    - name: Prettier
      run: npm run prettier:check
    - name: Build
      run: npm run build:prod
    - name: Test
      run: npm run test:ci
    - name: E2E
      run: npm run e2e:ci
